### ISSUE TITLE
Add two enrichers (one at the beginning and on at the end of list) that will add custom SQL statements

### ISSUE THREAD

**Issue by starnowski** [starnowski/posmulten#252]
Add two enrichers (one at the beginning and on at the end of list) that will add custom SQL statements.

EnumType - AT_BEGINNING, AT_END
addCustomSQLDefinition(String creationScript, EnumType type)
addCustomSQLDefinition(String creationScript, String deleteScript, EnumType type)
addCustomSQLDefinition(String creationScript, String deleteScript, List<String> validationScripts, EnumType type)

### Optional
Yaml configuration
```yaml
...
customSQLDefinitions:
  - type: AT_END
    creationScript: |
    ALTER ...

  - type: AT_BEGINNING
    creationScript: |
      ALTER ...
    deletionScript: |
      ALTER ...
    validationScripts:
    - |
      SELECT (1) FROM ...
    - "SELECT (1) ....."
```
