### ISSUE TITLE
Add feature that allows to specify custom sql definitions in configuration file

### ISSUE THREAD

**Issue by starnowski** [starnowski/posmulten#256]
Add a feature that allows specifying custom SQL definitions in the configuration file
See issue https://github.com/starnowski/posmulten/issues/252

### Optional
Yaml configuration
```yaml
...
custom_sql_definitions:
  - type: AT_END
    creation_script: |
    ALTER ...

  - type: AT_BEGINNING
    creation_script: |
      ALTER ...
    drop_script: |
      ALTER ...
    validation_scripts:
    - |
      SELECT (1) FROM ...
    - "SELECT (1) ....."
```
